[workspace]
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "saddle-search-practice"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.13"
rdkit = "<2024.09"
libgfortran = "14.*"
xtb = "<6.7"
ipykernel = "*"
autode = "*"

